//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscolaItau.Models
{
    using System.ComponentModel.DataAnnotations;

    public partial class Quadro
    {
        public int quadro_id { get; set; }

        [Required(ErrorMessage = "Selecione um(a) Professor(a)", AllowEmptyStrings = false)]
        [Display(Name = "Professor(a)")]
        public int fk_professor_id { get; set; }

        [Required(ErrorMessage = "Selecione uma Disciplina", AllowEmptyStrings = false)]
        [Display(Name = "Disciplina")]
        public int fk_disciplina_id { get; set; }
    
        public virtual Disciplina Disciplina { get; set; }
        public virtual Professor Professor { get; set; }
    }
}
